# Generated by Django 2.1.1 on 2018-10-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo_desc', models.ImageField(blank=True, upload_to='')),
                ('text_desc', models.TextField(blank=True)),
                ('address', models.ImageField(blank=True, upload_to='exhibition_detail_map')),
                ('no', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=10)),
                ('body', models.TextField(blank=True)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionTotalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='exhibition_list')),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ExhibitionTotalList'),
        ),
    ]
