# Generated by Django 2.1.1 on 2018-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitiontotallist',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibitiontotallist',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibitiontotallist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
