# Generated by Django 2.1.1 on 2018-09-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='img_profile',
        ),
    ]
